name: wolt_mobile_engineering_internship
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  build_runner: ^2.4.8
  cached_network_image: ^3.3.1
  custom_lint: ^0.5.11
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  geolocator: ^10.1.0
  http: ^1.2.0
  riverpod_annotation: ^2.3.3
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
